1. Write a Python Program to Add Two Matrices?
2. Write a Python Program to Multiply Two Matrices?
3. Write a Python Program to Transpose a Matrix?
4. Write a Python Program to Sort Words in Alphabetic Order?
5. Write a Python Program to Remove Punctuation From a String?

1)

In [ ]:
# if we use numpy array as matrices it is staigth forward to calulate these operations

In [20]:
import numpy as np

In [30]:
A = np.ones((5,5))
B = np.eye(5)
print(A+B)

[[2. 1. 1. 1. 1.]
 [1. 2. 1. 1. 1.]
 [1. 1. 2. 1. 1.]
 [1. 1. 1. 2. 1.]
 [1. 1. 1. 1. 2.]]


2)

In [31]:
A*B

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

3)

In [33]:
B.transpose()

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

4)

In [36]:
list_names = ['Sudhanshu', 'Krish','Sunny','Hitesh']
print(sorted(list_names, key=str.lower))

['Hitesh', 'Krish', 'Sudhanshu', 'Sunny']


5) 

In [42]:
import re
string = "She cried and kept talking, her sentences punctuated by sobs. "
print("The original string is : " + string)
res = re.sub(r'[^\w\s]', '', string)
print("The string after punctuation filter : " + res)

The original string is : She cried and kept talking, her sentences punctuated by sobs. 
The string after punctuation filter : She cried and kept talking her sentences punctuated by sobs 
